# ML lab 08: Tensor Mnipulation

In [1]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [3]:
t = np.array([[1., 2., 3.],
             [4., 5., 6.],
             [7., 8., 9.]])
pp.pprint(t)
print(t)
print(t.ndim)  # 몇차원인지
print(t.shape)  # 각 axis의 길이 (axis는 가장 바깥쪽부터 셈)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
2
(3, 3)


In [4]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval()

array([4], dtype=int32)

In [5]:
t = tf.constant([[1, 2],
                [3, 4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [6]:
t = tf.constant(
    [
        [
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
            ],
            [
                [13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]
            ]
        ]
    ]
)
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [7]:
# matmul

matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print(matrix1.shape)
print(matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

(2, 2)
(2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [8]:
# multiply

(matrix1 * matrix2).eval()

array([[1., 2.],
       [6., 8.]], dtype=float32)

In [9]:
# Broadcasting  자동으로 길이를 맞춰줌

matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval()

array([[5., 5.]], dtype=float32)

In [10]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
print((matrix1 + matrix2).eval())

[[4. 5.]]


In [11]:
tf.reduce_mean([1, 2], axis = 0).eval()  # 1.5가 안나오고 integer 1이 나온다.

1

In [12]:
x = tf.constant([[1., 2.],
     [3., 4.]])
tf.reduce_mean(x).eval()

2.5

In [13]:
print(tf.reduce_mean(x, axis = 0).eval())  # 0번째 axis의 길이를 1로 줄여라
print(x.shape, tf.reduce_mean(x, axis = 0).eval().shape)

[2. 3.]
(2, 2) (2,)


In [14]:
tf.reduce_mean(x, axis = 1).eval()

array([1.5, 3.5], dtype=float32)

In [15]:
tf.reduce_mean(x, axis = -1).eval()  # -1은 가장 깊이 있는 axis의 길이를 1로 만들어라(혹은 0으로 만들고 collapse)

array([1.5, 3.5], dtype=float32)

In [16]:
tf.reduce_sum(x, axis = 0).eval()

array([4., 6.], dtype=float32)

In [17]:
tf.reduce_sum(x, axis = 1).eval()

array([3., 7.], dtype=float32)

In [18]:
tf.reduce_mean(tf.reduce_sum(x, axis = -1)).eval()  # 먼저 제일 안쪽을 더해서 3과 7을 만들고 둘을 평균해서 5로 계산

5.0

In [19]:
x = [[0, 1, 2],
    [2, 1, 0]]
tf.math.argmax(x, axis = 0).eval()  # 가장 큰 값의 index를 찾는다.

array([1, 0, 0])

In [20]:
tf.argmax(x, axis = 1).eval()

array([2, 0])

In [21]:
tf.argmax(x, axis = -1).eval()  # axis = 1과 같음.

array([2, 0])

In [22]:
t = np.array(
    [
        [
            [0, 1, 2],
            [3, 4, 5]
        ],
        [
            [6, 7, 8],
            [9, 10, 11]
        ]
    ]
)
t.shape

(2, 2, 3)

In [23]:
# reshape
tf.reshape(t, shape = [-1, 3]).eval()  # dim = 2, shape = [4, 3]으로 reshape하겠다. (-1은 알아서 계산해서 채워라.)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
tf.reshape(t, shape = [-1, 1, 3]).eval()  # [4, 1, 3]

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [25]:
# squeeze
tf.squeeze(([0], [1], [2])).eval()  # 무조건 dim = 1로 만들어버리겠다.

array([0, 1, 2], dtype=int32)

In [26]:
# expand_dims
x = tf.constant([[0, 1, 2], [3, 4, 5]])
print(x.eval(), x.shape, '\n', sep = '\n')

x = tf.constant([[0, 1, 2], [3, 4, 5]])
x = tf.expand_dims(x, 0)
print(x.eval(), x.shape, '\n', sep = '\n')  # dim의 0번째에 axis길이 1짜리 차원을 1개 늘리겠다.

x = tf.constant([[0, 1, 2], [3, 4, 5]])
x = tf.expand_dims(x, 1)
print(x.eval(), x.shape, '\n', sep = '\n')  # dim의 1번째에 axis길이 1짜리 차원을 1개 늘리겠다.

x = tf.constant([[0, 1, 2], [3, 4, 5]])
x = tf.expand_dims(x, 2)
print(x.eval(), x.shape, '\n', sep = '\n')  # dim의 2번째에 axis길이 1짜리 차원을 1개 늘리겠다.

x = tf.constant([[0, 1, 2], [3, 4, 5]])
x = tf.expand_dims(x, -1)
print(x.eval(), x.shape, '\n', sep = '\n')  # dim의 마지막(2)번째에 axis길이 1짜리 차원을 1개 늘리겠다.

[[0 1 2]
 [3 4 5]]
(2, 3)


[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)


[[[0 1 2]]

 [[3 4 5]]]
(2, 1, 3)


[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3, 1)


[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3, 1)




In [27]:
# one_hot
x = tf.constant([[0], [1], [2], [0]])
y = tf.one_hot(x, depth = 3)  # 길이 3짜리 one_hot으로 만들거다. (0~2까지 있으니까 길이 3이 맞음)
print(y.eval(), '\n\n')
# 가장 안쪽의 axis가 추가된다고 보면 된다.
print(x.shape, y.shape) 

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]] 


(4, 1) (4, 1, 3)


In [28]:
tf.one_hot([0, 1, 2, 3], depth = 4).eval()  # 길이 4짜리 one_hot으로 만들거다

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [29]:
t = tf.one_hot(x, depth = 3)
tf.reshape(t, shape = [-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [30]:
# cast
tf.cast([1.8, 2.2, 3.3, 4.9], dtype = tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [31]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()  # dtype 생략 가능

array([1, 0, 1, 0], dtype=int32)

In [32]:
# stack
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [33]:
tf.stack([x, y, z], axis = 1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [34]:
tf.stack([x, y, z], axis = 0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [35]:
# Ones and Zeros like
x = [[0, 1, 2],
    [2, 1, 0]]

tf.ones_like(x).eval()  # 같은 shape을 가진 그대로 1을 채움

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [36]:
tf.zeros_like(x).eval()  # 같은 shape을 가진 그대로 0을 채움

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [37]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
