In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4,5], [6,34,3,5,3]])
b = np.array([[6,6,77,54,4], [4,3,56,6,2]])

In [9]:
np.square(a - b)

array([[  25,   16, 5476, 2500,    1],
       [   4,  961, 2809,    1,    1]])

In [10]:
np.mean(np.sum(np.square(a - b), axis = 1) / 2e+04)

array([8018, 3776])

In [11]:
np.sum(np.square(a - b), axis = 1)

array([8018, 3776])