# ML lab 04-1

In [1]:
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [2]:
tf.set_random_seed(777)  # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]))
w2 = tf.Variable(tf.random_normal([1]))
w3 = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = w1 * x1 + w2 * x2 + w3 * x3 + b

cost = tf.reduce_mean(tf.square(hypothesis - y))

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-5).minimize(cost)

In [3]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        _, hy_val, cost_val = sess.run([train, hypothesis, cost], 
                                       feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, y: y_data})
        if step % 100 == 0:
            print(step, hy_val, cost_val)

0 [-75.96345  -78.27629  -83.83015  -90.80436  -56.976482] 62547.29
100 [146.06377 188.31447 178.98654 195.37894 146.31259] 13.247167
200 [146.20279 188.21931 179.0293  195.4085  146.1889 ] 12.5621395
300 [146.3381  188.12671 179.07095 195.43723 146.06857] 11.913301
400 [146.46979 188.03654 179.11147 195.46513 145.95143] 11.298648
500 [146.59799 187.9488  179.15092 195.49231 145.83746] 10.716391
600 [146.72278 187.86342 179.18935 195.51869 145.72656] 10.164865
700 [146.84424 187.78029 179.22673 195.54436 145.61864] 9.642395
800 [146.96248 187.69937 179.26315 195.5693  145.51363] 9.147448
900 [147.07758 187.6206  179.29858 195.59357 145.41145] 8.678604
1000 [147.1896  187.54395 179.33308 195.61716 145.31201] 8.234464
1100 [147.29865 187.46933 179.36667 195.64008 145.21526] 7.8137703
1200 [147.4048  187.39668 179.39937 195.66235 145.12111] 7.415207
1300 [147.50812 187.326   179.43121 195.684   145.0295 ] 7.037703
1400 [147.6087  187.25717 179.46219 195.70505 144.94034] 6.680026
1500 [147

In [4]:
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape = [None, 3])
# 데이터가 몇개 들어올지는 모르고 feature는 3개다.
# [row, col]이 들어온다고 생각. 이때 데이터가 몇개 들어올지는 모르니까 None
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-5).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        _, hy_val, cost_val = sess.run([train, hypothesis, cost], 
                                       feed_dict = {X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, hy_val, cost_val, sep = '\n', end = '\n\n')

0
[[-159.22546]
 [-197.2163 ]
 [-191.33363]
 [-208.02669]
 [-152.1618 ]]
126121.6

100
[[155.73917]
 [181.59718]
 [181.78825]
 [198.3048 ]
 [136.83037]]
12.159109

200
[[155.61072]
 [181.68556]
 [181.74934]
 [198.27315]
 [136.94933]]
11.551899

300
[[155.48576]
 [181.77159]
 [181.7115 ]
 [198.2423 ]
 [137.06516]]
10.976598

400
[[155.36418]
 [181.8553 ]
 [181.6747 ]
 [198.21219]
 [137.17793]]
10.431516

500
[[155.24588]
 [181.93675]
 [181.6389 ]
 [198.18283]
 [137.28775]]
9.915052

600
[[155.13078]
 [182.01599]
 [181.60406]
 [198.15417]
 [137.39467]]
9.425737

700
[[155.01881]
 [182.09311]
 [181.57019]
 [198.12622]
 [137.49878]]
8.9621105

800
[[154.90987]
 [182.16814]
 [181.53726]
 [198.09897]
 [137.60016]]
8.522844

900
[[154.80386]
 [182.24115]
 [181.50522]
 [198.07234]
 [137.69887]]
8.1065855

1000
[[154.70074]
 [182.3122 ]
 [181.47406]
 [198.04639]
 [137.79498]]
7.712208

1100
[[154.60042]
 [182.3813 ]
 [181.44374]
 [198.02104]
 [137.88858]]
7.338505

1200
[[154.5028 ]
 [182.44856