# ML lab 04-2

In [1]:
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [2]:
import numpy as np
xy = np.loadtxt('/home/data/data-01-test-score.csv', delimiter = ',', dtype = np.float32)
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [3]:
x_data = xy[:, :-1]
y_data = xy[:, [-1]]
# 여기 -1을 [-1] 이렇게 넣지 않으면 Y = tf.placeholder(tf.float32, shape = [None, 1]) 여기 들어가질 않음
print(x_data.shape, x_data, y_data.shape, y_data, sep = '\n\n')

(25, 3)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]

(25, 1)

[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [4]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-5).minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, cost_val, hy_val, sep = '\n', end = '\n\n')

0
11120.572
[[256.6328 ]
 [301.73837]
 [300.81073]
 [326.61972]
 [229.35   ]
 [166.94348]
 [245.02592]
 [182.56328]
 [279.3175 ]
 [256.04474]
 [235.08345]
 [228.50943]
 [311.62183]
 [260.0235 ]
 [245.05397]
 [305.8942 ]
 [246.75192]
 [294.9176 ]
 [298.27737]
 [267.472  ]
 [286.65375]
 [282.59048]
 [274.15277]
 [260.7744 ]
 [314.19165]]

100
26.743925
[[157.4054  ]
 [182.80043 ]
 [183.44409 ]
 [198.89677 ]
 [138.63998 ]
 [100.256065]
 [149.47588 ]
 [111.79565 ]
 [168.3567  ]
 [153.51413 ]
 [143.02171 ]
 [137.91533 ]
 [190.27106 ]
 [159.02689 ]
 [149.12402 ]
 [185.26378 ]
 [150.54729 ]
 [180.23512 ]
 [182.52121 ]
 [163.88052 ]
 [174.61774 ]
 [171.08582 ]
 [167.27979 ]
 [160.50732 ]
 [190.82907 ]]

200
24.99333
[[157.21173 ]
 [182.87788 ]
 [183.35283 ]
 [198.89125 ]
 [138.6987  ]
 [100.480354]
 [149.52423 ]
 [111.89568 ]
 [168.61569 ]
 [153.98917 ]
 [143.06439 ]
 [138.13028 ]
 [190.0862  ]
 [158.75989 ]
 [149.22931 ]
 [185.40315 ]
 [150.27536 ]
 [180.28052 ]
 [182.28227 ]
 [163.65018 ]
 [

In [6]:
print(sess.run(hypothesis, feed_dict = {X: [[100, 70, 101]]}))  # test할때 X는 2차원으로 들어가야함.
print(sess.run(hypothesis, feed_dict = {X: [[60, 70, 110], [90, 100, 80]]}))

[[178.4763]]
[[170.55434]
 [181.70644]]


### 배치나누기

이해가 안된다

파일 자체가 너무 커서 한번에 읽기 곤란한 경우 혹은 파일 여러개에서 한번에 읽는 경우

1. 파일 합치기

```python
filename_queue = tf.train.string_input_producer(['data01', 'data02', ...], shuffle = False, name = 'filename_queue')
```
    
2. 읽기

```python
reder = tf.TextLineReader()
key, value = reader.read(filename_queue)
```
    
3. 값 parsing, 데이터 타입 정의 등..

```python
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)
```

In [7]:
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['/home/data/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]  # 각각 field의 데이터 타입
xy = tf.decode_csv(value, record_defaults=record_defaults)  # csv decode

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 100 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val, '\n\n')

coord.request_stop()
coord.join(threads)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base